version: '3.8'
services:
  app:
    environment:
      - JWT_SECRET=your-secret-key
    build:
      context: ./todo_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./todo_api:/var/www/todo-api
    container_name: todo-app-php
    depends_on:
      - db
    networks:
      - todo-network

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: todo-app-db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  db-data: